### Sign in
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "id": "ileilliat@gmail.com",
  "pw": "lsy1020"
}

### Sign out
POST http://localhost:3000/users/signout
Content-Type: application/json

{
}

### Sign up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "id": "qwerty@example.com",
  "pw": "qwertyisgood",
  "name": "한영",
  "detail": "안녕하세요 예제 이름입니다. :)",
  "phone": "010-0000-0000"
}