### Class list (all/16)
GET http://localhost:3000/class/all
Content-Type: application/json


### Class list (main/8)
GET http://localhost:3000/class/main
Content-Type: application/json


### Search - 프로그래밍
GET http://localhost:3000/class/search/프로그래밍
Content-Type: application/json


### Taking class (my)
GET http://localhost:3000/class/my/ileilliat@gmail.com
Content-Type: application/json


### Class info
GET http://localhost:3000/class/info/1
Content-Type: application/json


### Class info - fail
GET http://localhost:3000/class/info/50
Content-Type: application/json