### Class list (all/16)
GET http://localhost:3000/class/all
Content-Type: application/json


### Class list (main/8)
GET http://localhost:3000/class/main
Content-Type: application/json


### Search - 프로그래밍
GET http://localhost:3000/class/search/프로그래밍
Content-Type: application/json


### Class enrol
POST http://localhost:3000/class/enrol/11
Content-Type: application/json


### Taking class (my)
GET http://localhost:3000/class/my
Content-Type: application/json


### Class info
GET http://localhost:3000/class/info/1
Content-Type: application/json


### Class notice
GET http://localhost:3000/class/notice/1
Content-Type: application/json


### Class notice create
POST http://localhost:3000/class/notice/create
Content-Type: application/json

{
  "classId": "1",
  "title": "테스트 공지입니다.",
  "contents": "테스트 공지가 잘 작성되는지 확인합니다."
}


### Class notice update
POST http://localhost:3000/class/notice/update/2
Content-Type: application/json

{
  "title": "테스트 공지 수정",
  "contents": "수정된 내용인지 확인합니다."
}


### Class notice read
GET http://localhost:3000/class/notice/read/2
Content-Type: application/json


### Class notice delete
DELETE http://localhost:3000/class/notice/delete/2
Content-Type: application/json



### Class process
GET http://localhost:3000/class/process/ileilliat@gmail.com/1
Content-Type: application/json


### Class process (completed)
GET http://localhost:3000/class/process/ileilliat@gmail.com
Content-Type: application/json


### Class contents
GET http://localhost:3000/class/contents/1/1
Content-Type: application/json


### Class done - video
POST http://localhost:3000/class/done/video
Content-Type: application/json

{
  "classId": "1",
  "contentId": "2"
}

### Class done - test
POST http://localhost:3000/class/done/test
Content-Type: application/json

{
  "classId": "1",
  "contentId": "2",
  "answer": [
    "1번 답",
    "2번 답"
  ]
}

### Class done - test score
POST http://localhost:3000/class/done/test/score
Content-Type: application/json

{
  "classId": "1",
  "contentId": "2",
  "score": 100,
  "feedback": "정말 잘 풀었습니다."
}


### IsCompleted class
GET http://localhost:3000/class/complete/ileilliat@gmail.com/1
Content-Type: application/json